server:
  port: 8081
  servlet:
    context-path: /wxb_customer

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wfx?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password:

  redis:
    host: 192.168.220.140
    port: 6379
    password: 123456
    timeout: 3000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cyj.entity

logging:
  level:
    com.qisheng.mgjcrm.dao: debug
  config: classpath:log4j2-spring.xml # 指定log4j配置文件的位置

pagehelper:
  reasonable: true #配置参数合理化(当删除数据时，如果当前页数小于总页数会自动变化)